#!/bin/sh
#
#
# Copyright 2009 by William Astle <lost@l-w.ca>
#
#This file is part of LWTOOLS.
#
#LWTOOLS is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#This program is distributed in the hope that it will be useful, but WITHOUT
#ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
#more details.
#
#You should have received a copy of the GNU General Public License along with
#this program. If not, see <http://www.gnu.org/licenses/>.

# this was based somewhat on the "ar" script from gcc6809

# This script is a frontend to the lwar library manager, to make it
# look more like GNU ar.  Not all ar features are supported here.
# It basically translates ar style _options into lwar format.

# Parse and translate command-line _options

# ar _options cheatsheet:
# r: insert (with replace)
# c: create archive
# u: only replace newer files
# v: verbose mode
# x: extract files from archive

if [ "$#" == "0" ]; then
	echo "ar (m6809): no _options given"
	exit 1
fi

current_options=$1; shift
case $current_options in
	rc|cru|-rc|-cru)
		output_options="--replace --create"
		;;
	rv)
		output_options="--replace"
		;;
	x|-x)
		output_options="--extract"
		;;
	-C|--cache)
		exit 0
		;;
	*)
		output_options="--replace --create $_options"
		if [ "$libname" = "" ]; then
			libname=$output_options
		fi
		;;
esac

# Run the real lwar with translated _options.
# --nopaths is given to get the proper standard "ar" behaviour
# which doesn't store path names
exec lwar --nopaths $output_options $*
